"""Add created_at to InventoryCopy

Revision ID: 57bc09b7811d
Revises: eddc078df5c8
Create Date: 2025-12-04 01:12:32.393585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57bc09b7811d'
down_revision = 'eddc078df5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_copies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_copies', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
