"""Add donor_id to InventoryCopy

Revision ID: 5e2f93ab8cad
Revises: 1f4fb63bb0d2
Create Date: 2025-12-03 23:52:29.091344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2f93ab8cad'
down_revision = '1f4fb63bb0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_copies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_inventory_copies_donor_id', 'donors', ['donor_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('archived')

    with op.batch_alter_table('inventory_copies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('donor_id')

    # ### end Alembic commands ###
