"""Make Donor branch and batch nullable

Revision ID: eddc078df5c8
Revises: 5e2f93ab8cad
Create Date: 2025-12-04 00:29:08.713355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddc078df5c8'
down_revision = '5e2f93ab8cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
